@host = http://localhost:5000
@token =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJub21lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbUBjbWRiLmNvbS5iciIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTc0MzQ1Njk1MCwiZXhwIjoxNzQzNTQzMzUwLCJpYXQiOjE3NDM0NTY5NTB9.Ei6sm06XwII2MO3SreKbjFb2x0kSHwTLt2B06gFEoBA


###
POST {{host}}/Api/IC/IC/Pesquisa
Accept: application/json
Authorization: {{token}}
Content-Type: application/json

{
  "Chave": "nome teste",
  "Ativo": true,
  "FilhoDe": null,
  "Tipo": 1
}


