@host = http://localhost:5001
@token =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJub21lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbUBjbWRiLmNvbS5iciIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTc1Mjk2NzYxNSwiZXhwIjoxNzUzMDU0MDE1LCJpYXQiOjE3NTI5Njc2MTV9.4CpDEyhcxanmP7KofuXzGXAg1EBmscAtjJ3Sxz0re-c

### novo
POST {{host}}/Api/Seg/Usuario/Novo
Accept: application/json
Content-Type: application/json

{
  "id": 0,
  "nome": "usr",
  "email": "user1@cmdb.com.br",
  "administrador": false,
  "ativo": true,
  "senha": "123456"
}

### login

POST {{host}}/Api/Seg/Usuario/login
Accept: application/json
Content-Type: application/json

{
  "email": "adm@cmdb.com.br",
  "senha": "123456"
}

### lista
GET {{host}}/Api/Seg/Usuario/Lista
Authorization: {{token}}
Accept: application/json
