@host = http://localhost:5000
@token =Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJub21lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbUBjbWRiLmNvbS5iciIsInJvbGUiOiJhZG1pbiIsIm5iZiI6MTczMTg3NDQxOCwiZXhwIjoxNzMxOTYwODE4LCJpYXQiOjE3MzE4NzQ0MTh9.UwX_Abfo1G_n54P_dv8Joaa1ktJ0g_xtx6z2fFAvw7Y

###
POST {{host}}/Api/Seg/Usuario/Novo
Accept: application/json
Content-Type: application/json

{
  "id": 0,
  "nome": "admin",
  "email": "user@cmdb.com.br",
  "administrador": false,
  "ativo": true,
  "senha": "123456"
}

###

POST {{host}}/Api/Seg/Usuario/login
Accept: application/json
Content-Type: application/json

{
  "email": "adm@cmdb.com.br",
  "senha": "123456"
}

###
GET {{host}}/Api/Seg/Usuario/Lista
Authorization: {{token}}
Accept: application/json
